### ISSUE TITLE
Pin label compatibility

### ISSUE THREAD

**Issue by riklaunim** [micropython-IMU/micropython-bmp180#3]
I had to change the pin int numbers to Pin.board labels or latest MicroPython version would throw exceptions that it can't implicitly convert int to str.

```
 I2C(scl=Pin(Pin.board.Y9), sda=Pin(Pin.board.Y10), freq=100000)
```

**Comment by turbinenreiter** [comment]
I changed the class to take an i2c object as argument to avoid issues like this in the future. Check out the new doc.

**Comment by riklaunim** [comment]
I2C.MASTER doesn't exist for machine.I2C. It exists for pyb.I2C.

**Comment by turbinenreiter** [comment]
The whole Hardware API is being overhauled right now - I will update the example again when there is a final version.
