### ISSUE TITLE
Read pressure/altitude fails with struct.error exception

### ISSUE THREAD

**Issue by halmartin** [micropython-IMU/micropython-bmp180#4]
I just received a Wemos D1 Mini and BMP180 pressure sensor.

Trying this library, I'm getting `0.0` for pressure and altitude. Looking at `bmp180.py`, it seems this is the result if `struct.unpack` returns an exception while unpacking. 

Unless I have misunderstood the purpose of [L153-155](https://github.com/micropython-IMU/micropython-bmp180/blob/master/bmp180.py#L153), the library is trying to unpack `MSB`, `LSB`, and `XLSB` as [little endian integers](https://docs.python.org/2/library/struct.html).

However above on lines [105-107](https://github.com/micropython-IMU/micropython-bmp180/blob/master/bmp180.py#L105), it is only reading 1 byte from each `{M,L,XL}SB` register.

This will cause a `struct.error` exception to be thrown when trying to unpack as a little endian integer, as `struct.unpack` is expecting at least two bytes, but only one byte has been read from the register. Tested in full Python interpreter:
```
# MSB_raw value returned from sensor via i2c.readfrom_mem(119,0xF6,1)
>>> MSB_raw = b'\x9e'
>>> MSB = unp('<h', MSB_raw)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: unpack requires a buffer of 2 bytes
```

[Page 18 on the Bosch datasheet](https://cdn-shop.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf) seems to confirm that `MSB`, `LSB`, and `XLSB` are only one byte, not two.

Shouldn't L153-155 be instead:
```
            MSB = unp('B', self.MSB_raw)[0]
            LSB = unp('B', self.LSB_raw)[0]
            XLSB = unp('B', self.XLSB_raw)[0]
```

With this modification, I'm getting somewhat sensible values from the sensor:
```
>>> bmp180.pressure
b'\x9e'
b'0'
b'@'
96486.3
>>> bmp180.altitude
b'\x9e'
b'4'
b'\xc0'
389.85
```
(The altitude of my location is ~500m)

Here are the compvalues for my BMP180:
```
>>> bmp180.compvaldump()
[8230, -1187, -14490, 33554, 24764, 22644, 6515, 47, -32768, -11786, 2964, 2]
```

**Comment by turbinenreiter** [comment]
I haven't touched this code in a while, but what you explain seems quite reasonable. This code definitely worked back in the days, maybe I accidentally relied on a different bug in the interpreter.

If you figure it out, I'd be happy about a pull request. If you are interested, I can also add you to the organization, so you can become a maintainer.

**Comment by halmartin** [comment]
@turbinenreiter I'm happy to submit a pull request for these changes. I only have one BMP180 sensor, so it's difficult for me to confirm whether the behaviour is sane or not.

I'll submit a pull request with the changes and perhaps someone else using this library with a BMP180 can confirm they are also seeing the expected readings.

**Comment by halmartin** [comment]
Sorry for the delay, I'd forgotten about this until now.

Pull request is here: https://github.com/micropython-IMU/micropython-bmp180/pull/5
